[package]
name = "kinode_process_lib"
version = "0.5.8"
edition = "2021"

[features]
eth = [ "ethers-core", "alloy-rpc-types" ]

[dependencies]
alloy-rpc-types = { git = "https://github.com/alloy-rs/alloy.git", rev = "3b1c310", optional = true }
anyhow = "1.0"
bincode = "1.3.3"
ethers-core = { version = "2.0.11", optional = true }
http = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
thiserror = "1.0"
url = "2.4.1"
mime_guess = "2.0"
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "efcc759" }
